//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JurisUtilityBase.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JurisUtilityBase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	FldMatter.FldMatter, 
        ///	FldClient.FldClient
        ///FROM
        ///	(SELECT     
        ///		SpTxtValue AS FldMatter
        ///	FROM
        ///		SysParam
        ///        WHERE      
        ///		(SpName = &apos;FldMatter&apos;)
        ///	) AS FldMatter 
        ///CROSS JOIN 
        ///	(SELECT     
        ///		SpTxtValue AS FldClient 
        ///	 FROM          
        ///		SysParam AS SysParam_1
        ///         WHERE      
        ///		(SpName = &apos;FldClient&apos;)
        ///	) AS FldClient.
        /// </summary>
        internal static string GetFieldLengths {
            get {
                return ResourceManager.GetString("GetFieldLengths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declare @vDate    datetime 
        ///set nocount on
        ///select 
        ///	@vDate = max(backup_finish_date) 
        ///from 
        ///	msdb.dbo.backupset 
        ///where 
        ///	database_name =  &apos;#DATABASE#&apos; and backup_finish_date &lt;= GetDate()
        ///if @vDate is null
        ///	select 
        ///		@vDate = crdate 
        ///	from 
        ///		master.dbo.sysdatabases 
        ///	where name = &apos;#DATABASE#&apos;
        ///select @vDate as LastBackupDate
        ///set nocount off.
        /// </summary>
        internal static string GetLastBackupDate {
            get {
                return ResourceManager.GetString("GetLastBackupDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server=#SERVER#;Database=#DATABASE#;UID=#USERID#;PWD=#DATA#;Trusted_Connection=NO.
        /// </summary>
        internal static string SqlConnectionString {
            get {
                return ResourceManager.GetString("SqlConnectionString", resourceCulture);
            }
        }
    }
}
